### ISSUE TITLE
Tables does not render properly

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/dokka-site#25]
Our tables gets render as divs (and documentation structure) rather then html tables. 
![Screenshot from 2020-09-09 01-53-53](https://user-images.githubusercontent.com/3967938/92538578-5750dc80-f23f-11ea-811e-a2ee6ec76f6b.png)

**Comment by mkondratek** [comment]
Expected:

![image](https://user-images.githubusercontent.com/19799111/93480279-8e895280-f8fd-11ea-8056-191fc9ce5e3b.png)


The first div content (grayed out) appears within the second div (which is wrong and result in the issue)
![image](https://user-images.githubusercontent.com/19799111/93480867-3acb3900-f8fe-11ea-9fc4-850fb3a09e3f.png)

**Comment by mkondratek** [comment]
I assume that this one comes from there: `org.jetbrains.dokka.base.renderers.html#HtmlRenderer.kt:359`

edit
**around line 403**

![image](https://user-images.githubusercontent.com/19799111/93596607-e6858f00-f9b9-11ea-873b-955466b2a1d6.png)

**Comment by mkondratek** [comment]
as @pikinier20 said in the https://github.com/VirtusLab/dokka-site/pull/34#issuecomment-709294525, this bug is from dokka

**Comment by mkondratek** [comment]
or better close it once the new version of Dokka containing the fix is released...
present https://github.com/Kotlin/dokka/releases/tag/v1.4.10 does not have it yet
